M48
; DRILL file {KiCad (6.0.10-0)} date Friday, February 17, 2023 at 04:15:33 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-17T16:15:33-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.2295Y-3.6748
X5.8571Y-3.4724
T2
X5.4433Y-2.7642
X5.6433Y-2.7642
T0
M30
